# Generated by Django 2.2.10 on 2020-05-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='RODZAJ PRODUKTU')),
                ('amount', models.CharField(default='', help_text='In ml', max_length=15, verbose_name='Amount of liquor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='NAZWA PRODUKTU')),
                ('prize', models.CharField(help_text='In zl', max_length=10, verbose_name='Cena jednostkowa')),
                ('description', models.CharField(default='', help_text='Opis Produktu', max_length=150, verbose_name='OPIS')),
                ('types', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.TypeOfProduct', verbose_name='RODZAJ PRODUKTU')),
            ],
        ),
    ]
