# Generated by Django 2.2.10 on 2020-02-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Type of Product')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Name')),
                ('amount', models.CharField(help_text='In ml', max_length=8, verbose_name='Amount of liquor')),
                ('prize', models.CharField(help_text='In zl', max_length=10, verbose_name='Prize for one portion')),
                ('type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.TypeOfProduct', verbose_name='Type of Product')),
            ],
        ),
    ]
