# Generated by Django 3.0.3 on 2020-02-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Name')),
                ('kind', models.CharField(default='', max_length=100, unique=True, verbose_name='Type of a liquor')),
                ('amount', models.PositiveIntegerField(help_text='In ml', verbose_name='Amount of liquor')),
                ('prize', models.PositiveIntegerField(help_text='In zl', verbose_name='Prize for one portion')),
            ],
        ),
    ]
