# Generated by Django 3.0.3 on 2020-02-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='kind',
            field=models.CharField(default='', max_length=100, verbose_name='Type of a liquor'),
        ),
    ]
