# Generated by Django 2.2.10 on 2020-05-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', help_text='Opis Produktu', max_length=150, verbose_name='Opis produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.TypeOfProduct', verbose_name='Rodzaj produktu'),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='amount',
            field=models.CharField(default='', help_text='In ml', max_length=15, verbose_name='Ilosc'),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa kategorii'),
        ),
    ]
