# Generated by Django 2.2.10 on 2020-02-17 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200214_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(help_text='In ml', verbose_name='Amount of liquor')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='amount',
        ),
        migrations.AlterField(
            model_name='menu',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Kind'),
        ),
    ]
