# Generated by Django 2.2.10 on 2020-02-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Type of Product'),
        ),
    ]
