# Generated by Django 2.2.10 on 2020-02-24 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200217_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Name')),
                ('amount', models.CharField(help_text='In ml', max_length=8, verbose_name='Amount of liquor')),
                ('prize', models.PositiveIntegerField(help_text='In zl', verbose_name='Prize for one portion')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='kind',
        ),
        migrations.DeleteModel(
            name='Kind',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
