# Generated by Django 2.2.10 on 2020-02-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200227_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.AddField(
            model_name='typeofproduct',
            name='amount',
            field=models.CharField(default='&mdash', help_text='In ml', max_length=8, verbose_name='Amount of liquor'),
        ),
    ]
