# Generated by Django 2.2.10 on 2020-02-24 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200224_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prize',
            field=models.CharField(help_text='In zl', max_length=10, verbose_name='Prize for one portion'),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='menu.Product'),
        ),
    ]
