# Generated by Django 2.2.10 on 2020-02-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200224_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproduct',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Type of Product'),
        ),
    ]
