# Generated by Django 2.2.10 on 2020-03-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200227_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='&nbsp;', help_text='Opis Produktu', max_length=150, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='amount',
            field=models.CharField(default='&mdash', help_text='In ml', max_length=15, verbose_name='Amount of liquor'),
        ),
    ]
