# Generated by Django 2.2.10 on 2020-02-26 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200227_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='menu.Product'),
        ),
    ]
