# Generated by Django 2.2.10 on 2020-05-15 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('limit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='BIBA', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('term_of_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('nr_of_people', models.PositiveIntegerField(default=2)),
                ('catering', models.BooleanField(default=False)),
                ('faktura', models.BooleanField(default=False)),
                ('additional_information', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'WSTĘPNA'), ('confirmed', 'POTWIERDZONA'), ('rejected', 'ODRZUCONA')], default='draft', max_length=10)),
                ('bar', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reservation.Bar', verbose_name='BAR')),
            ],
        ),
    ]
