# Generated by Django 3.0.2 on 2020-01-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField(max_length=9)),
                ('bar', models.CharField(choices=[('2 BAR', 'sala balowa z lozami'), ('3 BAR', 'sala biesiadna, koncertowa'), ('4 BAR', 'gorny bar')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'wstepna'), ('confirmed', 'potwierdzona')], max_length=10)),
                ('catering', models.CharField(choices=[(True, 'Tak'), (False, 'Nie')], default=False, max_length=5)),
                ('faktura', models.CharField(choices=[(True, 'Tak'), (False, 'Nie')], default=False, max_length=5)),
                ('additional_information', models.CharField(max_length=500)),
            ],
        ),
    ]
