# Generated by Django 3.0.2 on 2020-01-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nr_of_people',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='slug',
            field=models.SlugField(default='dupa', max_length=200, unique_for_date='term_of_reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='term_of_reservation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='catering',
            field=models.CharField(choices=[('1', 'Tak'), ('0', 'Nie')], default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=200, unique_for_date='term'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='faktura',
            field=models.CharField(choices=[('1', 'Tak'), ('0', 'Nie')], default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
    ]
