# Generated by Django 2.2.10 on 2020-05-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
