# Generated by Django 3.0.2 on 2020-01-30 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200130_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=200, unique_for_date='term_of_reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='term_of_reservation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
