# Generated by Django 3.0.2 on 2020-02-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20200130_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='slug',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='additional_information',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='catering',
            field=models.CharField(choices=[('Y', 'Tak'), ('N', 'Nie')], default='N', max_length=5),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='faktura',
            field=models.CharField(choices=[('Y', 'Tak'), ('N', 'Nie')], default='N', max_length=5),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nr_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('draft', 'wstepna'), ('confirmed', 'potwierdzona'), ('rejected', 'odrzucona')], max_length=10),
        ),
    ]
