# Generated by Django 2.2.10 on 2020-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200517_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='additional_information',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='catering',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='faktura',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
