# Generated by Django 3.0.2 on 2020-02-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200201_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='limit',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bar',
            name='name',
            field=models.CharField(default='Bar1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservation.Bar'),
        ),
    ]
