# Generated by Django 2.2.10 on 2020-05-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20200517_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='catering',
            field=models.BooleanField(choices=[('0', False), ('1', True)], default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='faktura',
            field=models.BooleanField(choices=[('0', False), ('1', True)], default=0),
        ),
    ]
