# Generated by Django 2.2.10 on 2020-05-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20200517_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='catering',
            field=models.BooleanField(blank=True, default=False, verbose_name='catering?'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='faktura',
            field=models.BooleanField(blank=True, default=False, verbose_name='faktura?'),
        ),
    ]
