# Generated by Django 2.2.10 on 2020-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20200517_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='catering',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='faktura',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
    ]
