# Generated by Django 2.2.10 on 2020-03-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_reservation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reservation.Bar', verbose_name='BAR'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nr_of_people',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('draft', 'WSTĘPNA'), ('confirmed', 'POTWIERDZONA'), ('rejected', 'ODRZUCONA')], default='draft', max_length=10),
        ),
    ]
